groups:
  - name: app_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_errors_total[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High HTTP error rate"
          description: "Error rate is above 5% for the last 5 minutes"

      - alert: HighLatency
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High HTTP request latency"
          description: "Average request latency is above 2 seconds"

      - alert: TooManyDBConnections
        expr: db_connections > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Too many database connections"
          description: "Number of active database connections is above 100"

      - alert: HighActiveUsers
        expr: active_users > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of active users"
          description: "Number of active users is above 1000" 